const S=(slug,name,url,category='telecom')=>({slug,name,url,category});

const pageExtras={
  'services-hub':[
    S('verizon-consumer','Verizon','https://www.verizon.com/'),S('att-consumer','AT&T','https://www.att.com/'),S('tmobile-consumer','T-Mobile','https://www.t-mobile.com/'),S('telstra-consumer','Telstra','https://www.telstra.com.au/'),S('optus-consumer','Optus','https://www.optus.com.au/'),S('spark-nz','Spark NZ','https://www.spark.co.nz/'),S('one-nz','One NZ','https://one.nz/'),S('singtel-consumer','Singtel','https://www.singtel.com/personal'),S('globe-ph','Globe','https://www.globe.com.ph/'),S('smart-ph','Smart','https://smart.com.ph/'),S('airtel-india','Airtel','https://www.airtel.in/')
  ],
  'personal-mobile':[
    S('verizon-prepaid','Verizon Prepaid','https://www.verizon.com/plans/prepaid/'),S('att-prepaid','AT&T Prepaid','https://www.att.com/prepaid/plans/'),S('tmobile-prepaid','T-Mobile Prepaid','https://prepaid.t-mobile.com/prepaid-plans'),S('telstra-prepaid','Telstra Prepaid','https://www.telstra.com.au/mobile-phones/prepaid-mobiles/offers-and-rates'),S('optus-prepaid','Optus Prepaid','https://www.optus.com.au/prepaid/plans'),S('spark-prepaid','Spark Prepaid','https://www.spark.co.nz/shop/mobile-plans/prepaid'),S('one-nz-prepay','One NZ Prepay','https://one.nz/mobile/prepay/'),S('singtel-prepaid','Singtel Prepaid','https://www.singtel.com/personal/products-services/mobile/prepaid-plans'),S('globe-prepaid','Globe Prepaid','https://www.globe.com.ph/prepaid'),S('smart-prepaid','Smart Prepaid','https://smart.com.ph/Prepaid'),S('airtel-prepaid','Airtel Prepaid','https://www.airtel.in/prepaid-recharge/')
  ],
  'affordable-home-data':[
    S('verizon-home','Verizon Home Internet','https://www.verizon.com/home/internet/'),S('att-fiber','AT&T Fiber','https://www.att.com/internet/fiber/'),S('tmobile-home','T-Mobile Home Internet','https://www.t-mobile.com/home-internet'),S('telstra-internet','Telstra Internet','https://www.telstra.com.au/internet'),S('optus-internet','Optus Broadband','https://www.optus.com.au/broadband-nbn'),S('spark-broadband','Spark Broadband','https://www.spark.co.nz/shop/internet'),S('one-nz-broadband','One NZ Broadband','https://one.nz/broadband/'),S('singtel-broadband','Singtel Broadband','https://www.singtel.com/personal/products-services/broadband'),S('globe-home','Globe At Home','https://new.globe.com.ph/gfiber'),S('pldt-home','PLDT Home','https://pldthome.com/'),S('airtel-broadband','Airtel Broadband','https://www.airtel.in/broadband/')
  ],
  'special-home-passes':[
    S('verizon-deals','Verizon Deals','https://www.verizon.com/deals/'),S('att-deals','AT&T Deals','https://www.att.com/deals/'),S('tmobile-offers','T-Mobile Offers','https://www.t-mobile.com/offers'),S('telstra-deals','Telstra Deals','https://www.telstra.com.au/deals'),S('optus-deals','Optus Deals','https://www.optus.com.au/deals'),S('spark-deals','Spark Deals','https://www.spark.co.nz/deals'),S('one-nz-offers','One NZ Offers','https://one.nz/offers/'),S('singtel-promotions','Singtel Promotions','https://www.singtel.com/personal/products-services/promotions'),S('globe-promos','Globe Prepaid Promos','https://www.globe.com.ph/prepaid'),S('smart-promos','Smart Prepaid','https://smart.com.ph/Prepaid'),S('airtel-offers','Airtel Offers','https://www.airtel.in/offers/')
  ],
  'u-tokmoa':[
    S('verizon-home','Verizon Home Internet','https://www.verizon.com/home/internet/'),S('att-home-phone','AT&T Home Phone','https://www.att.com/home-phone/'),S('telstra-home-phone','Telstra Home Phone','https://www.telstra.com.au/home-phone'),S('optus-home-internet','Optus Home Internet','https://www.optus.com.au/broadband-nbn'),S('spark-landline','Spark Landline','https://www.spark.co.nz/shop/landline'),S('one-nz-broadband','One NZ Broadband','https://one.nz/broadband/'),S('singtel-home','Singtel Home','https://www.singtel.com/personal/products-services/broadband'),S('globe-home','Globe At Home','https://new.globe.com.ph/gfiber'),S('pldt-home','PLDT Home','https://pldthome.com/'),S('airtel-broadband','Airtel Broadband','https://www.airtel.in/broadband/'),S('jiofiber','JioFiber','https://www.jio.com/fiber')
  ],
  'home-entertainment':[
    S('verizon-fios-tv','Verizon Fios TV','https://www.verizon.com/home/fios-tv/'),S('att-tv','AT&T TV','https://www.att.com/tv/'),S('telstra-entertainment','Telstra Entertainment','https://www.telstra.com.au/entertainment'),S('optus-subhub','Optus SubHub','https://www.optus.com.au/subhub'),S('spark-entertainment','Spark Entertainment','https://www.spark.co.nz/shop/entertainment'),S('one-nz-tv','One NZ TV','https://one.nz/tv/'),S('singtel-tv','Singtel TV','https://www.singtel.com/personal/products-services/tv'),S('pldt-home','PLDT Home','https://pldthome.com/'),S('globe-home','Globe At Home','https://new.globe.com.ph/gfiber'),S('jiofiber','JioFiber','https://www.jio.com/fiber'),S('airtel-xstream','Airtel Xstream Fiber','https://www.airtel.in/broadband/')
  ],
  'devices':[
    S('att-phones','AT&T Phones','https://www.att.com/buy/phones/'),S('tmobile-phones','T-Mobile Phones','https://www.t-mobile.com/cell-phones'),S('telstra-phones','Telstra Phones','https://www.telstra.com.au/mobile-phones/mobiles-on-a-plan'),S('optus-phones','Optus Phones','https://www.optus.com.au/mobile/phones'),S('spark-phones','Spark Phones','https://www.spark.co.nz/shop/mobile/phones'),S('one-nz-phones','One NZ Phones','https://one.nz/mobile/phones/'),S('singtel-phones','Singtel Phones','https://www.singtel.com/personal/products-services/mobile/phones'),S('globe-devices','Globe Devices','https://new.globe.com.ph/mobile/postpaid/devices'),S('smart-devices','Smart Devices','https://smart.com.ph/Postpaid/devices'),S('jio-devices','Jio Devices','https://www.jio.com/jcms/devices/'),S('brian-bell','Brian Bell Homecentres','https://www.brianbellonline.com/','png-business')
  ],
  'business-fixed':[
    S('verizon-business-internet','Verizon Business Internet','https://www.verizon.com/business/products/internet/'),S('att-business-internet','AT&T Business Internet','https://www.business.att.com/categories/internet.html'),S('tmobile-business-internet','T-Mobile Business Internet','https://www.t-mobile.com/business/solutions/business-internet-services'),S('telstra-enterprise','Telstra Enterprise','https://www.telstra.com.au/business-enterprise'),S('optus-enterprise','Optus Enterprise','https://www.optus.com.au/enterprise'),S('spark-business','Spark Business','https://www.spark.co.nz/business'),S('one-nz-business','One NZ Business','https://one.nz/business/'),S('singtel-enterprise','Singtel Enterprise','https://www.singtel.com/business'),S('airtel-business','Airtel Business','https://www.airtel.in/business/'),S('png-dataco','PNG DataCo','https://www.pngdataco.com/','png-public-enterprise'),S('nicta-png','NICTA PNG','https://www.nicta.gov.pg/','png-government')
  ],
  'business-mobile':[
    S('verizon-business-mobile','Verizon Business Mobile','https://www.verizon.com/business/products/mobile/plans/'),S('att-business-wireless','AT&T Business Wireless','https://www.business.att.com/products/wireless-plans.html'),S('tmobile-business-plans','T-Mobile Business Plans','https://www.t-mobile.com/business/wireless-business-plans'),S('telstra-business-mobile','Telstra Business Mobile','https://www.telstra.com.au/small-business/mobile-phones'),S('optus-business-mobile','Optus Business Mobile','https://www.optus.com.au/business/mobile'),S('spark-business-mobile','Spark Business Mobile','https://www.spark.co.nz/business/mobile'),S('one-nz-business-mobile','One NZ Business Mobile','https://one.nz/business/mobile/'),S('singtel-business-mobile','Singtel Business Mobile','https://www.singtel.com/business/products-services/mobility'),S('airtel-business-mobile','Airtel Business Mobility','https://www.airtel.in/business/b2b/mobility/'),S('bsp-bank','BSP Bank','https://www.bsp.com.pg/','png-business'),S('kina-bank','Kina Bank','https://www.kina.com.pg/','png-business')
  ],
  'news-media':[
    S('att-newsroom','AT&T Newsroom','https://about.att.com/pages/newsroom'),S('telstra-news','Telstra News','https://www.telstra.com.au/exchange'),S('air-niugini','Air Niugini','https://airniuginipng.com/','png-business'),S('bsp-bank','BSP Bank','https://www.bsp.com.pg/','png-business'),S('kina-bank','Kina Bank','https://www.kina.com.pg/','png-business'),S('steamships','Steamships','https://www.steamships.com.pg/','png-business'),S('trukai','Trukai Industries','https://www.trukai.com.pg/','png-business'),S('treasury-png','PNG Treasury','https://www.treasury.gov.pg/','png-government'),S('dict-png','PNG Department of ICT','https://www.ict.gov.pg/','png-government'),S('nicta-png','NICTA PNG','https://www.nicta.gov.pg/','png-government'),S('bankpng','Bank of Papua New Guinea','https://www.bankpng.gov.pg/','png-government')
  ],
  'about-us':[
    S('air-niugini','Air Niugini','https://airniuginipng.com/','png-business'),S('bsp-bank','BSP Bank','https://www.bsp.com.pg/','png-business'),S('kina-bank','Kina Bank','https://www.kina.com.pg/','png-business'),S('nambawan-super','Nambawan Super','https://www.nambawansuper.com.pg/','png-business'),S('nasfund','Nasfund','https://www.nasfund.com.pg/','png-business'),S('steamships','Steamships','https://www.steamships.com.pg/','png-business'),S('trukai','Trukai Industries','https://www.trukai.com.pg/','png-business'),S('png-lng','PNG LNG','https://pnglng.com/','png-business'),S('kumul-petroleum','Kumul Petroleum','https://kumulpetroleum.com/','png-public-enterprise'),S('dict-png-about','PNG Department of ICT About','https://www.ict.gov.pg/about-us/','png-government'),S('nicta-png-about','NICTA About','https://www.nicta.gov.pg/about-us/','png-government')
  ],
  'store-locator':[
    S('verizon-stores','Verizon Store Locator','https://www.verizon.com/stores/'),S('tmobile-stores','T-Mobile Store Locator','https://www.t-mobile.com/stores/locator'),S('telstra-stores','Telstra Store Locator','https://www.telstra.com.au/find-us'),S('optus-stores','Optus Store Locator','https://www.optus.com.au/stores'),S('spark-stores','Spark Store Finder','https://www.spark.co.nz/store-finder'),S('one-nz-stores','One NZ Stores','https://one.nz/stores/'),S('bsp-bank','BSP Bank Branch Context','https://www.bsp.com.pg/','png-business'),S('kina-bank','Kina Bank','https://www.kina.com.pg/','png-business'),S('brian-bell','Brian Bell Homecentres','https://www.brianbellonline.com/','png-business'),S('cpl-group','CPL Group','https://www.cpl.com.pg/','png-business'),S('png-power','PNG Power','https://www.pngpower.com.pg/','png-public-enterprise')
  ],
  'careers':[
    S('tmobile-careers','T-Mobile Careers','https://careers.t-mobile.com/'),S('telstra-careers','Telstra Careers','https://www.telstra.com.au/careers'),S('air-niugini','Air Niugini','https://airniuginipng.com/','png-business'),S('bsp-bank','BSP Bank','https://www.bsp.com.pg/','png-business'),S('kina-bank','Kina Bank','https://www.kina.com.pg/','png-business'),S('steamships','Steamships','https://www.steamships.com.pg/','png-business'),S('trukai','Trukai Industries','https://www.trukai.com.pg/','png-business'),S('png-lng','PNG LNG','https://pnglng.com/','png-business'),S('dict-png','PNG Department of ICT','https://www.ict.gov.pg/','png-government'),S('treasury-png','PNG Treasury','https://www.treasury.gov.pg/','png-government'),S('dpm-png','PNG Department of Personnel Management','https://www.dpm.gov.pg/','png-government')
  ],
  'faqs':[
    S('verizon-support','Verizon Support','https://www.verizon.com/support/'),S('att-support','AT&T Support','https://www.att.com/support/'),S('tmobile-support','T-Mobile Support','https://www.t-mobile.com/support'),S('telstra-support','Telstra Support','https://www.telstra.com.au/support'),S('optus-support','Optus Support','https://www.optus.com.au/support'),S('spark-help','Spark Help','https://www.spark.co.nz/help'),S('one-nz-help','One NZ Help','https://one.nz/faq/'),S('singtel-support','Singtel Support','https://www.singtel.com/personal/support'),S('bsp-bank','BSP Bank','https://www.bsp.com.pg/','png-business'),S('dict-png','PNG Department of ICT','https://www.ict.gov.pg/','png-government'),S('nicta-png','NICTA PNG','https://www.nicta.gov.pg/','png-government')
  ],
  'contact':[
    S('att-contact','AT&T Contact','https://www.att.com/support/contact-us/'),S('telstra-contact','Telstra Contact','https://www.telstra.com.au/contact-us'),S('air-niugini','Air Niugini','https://airniuginipng.com/','png-business'),S('bsp-bank','BSP Bank','https://www.bsp.com.pg/','png-business'),S('kina-bank','Kina Bank','https://www.kina.com.pg/','png-business'),S('nambawan-super','Nambawan Super','https://www.nambawansuper.com.pg/','png-business'),S('nasfund','Nasfund','https://www.nasfund.com.pg/','png-business'),S('dict-png','PNG Department of ICT','https://www.ict.gov.pg/','png-government'),S('treasury-png','PNG Treasury','https://www.treasury.gov.pg/','png-government'),S('nicta-png','NICTA PNG','https://www.nicta.gov.pg/','png-government'),S('bankpng','Bank of Papua New Guinea','https://www.bankpng.gov.pg/','png-government')
  ]
};

const contextCohorts=[
  {id:'context-png-businesses',name:'PNG Business Context',task_title:'Research Context - PNG Businesses',sources:[
    S('air-niugini','Air Niugini','https://airniuginipng.com/','png-business'),S('png-air','PNG Air','https://pngair.com.pg/','png-business'),S('bsp-bank','BSP Bank','https://www.bsp.com.pg/','png-business'),S('kina-bank','Kina Bank','https://www.kina.com.pg/','png-business'),S('nambawan-super','Nambawan Super','https://www.nambawansuper.com.pg/','png-business'),S('nasfund','Nasfund','https://www.nasfund.com.pg/','png-business'),S('brian-bell','Brian Bell Homecentres','https://www.brianbellonline.com/','png-business'),S('cpl-group','CPL Group','https://www.cpl.com.pg/','png-business'),S('steamships','Steamships','https://www.steamships.com.pg/','png-business'),S('trukai','Trukai Industries','https://www.trukai.com.pg/','png-business'),S('sp-brewery','SP Brewery','https://www.sp.com.pg/','png-business'),S('paradise-foods','Paradise Foods','https://www.paradisefoods.com.pg/','png-business'),S('png-lng','PNG LNG','https://pnglng.com/','png-business'),S('kumul-petroleum','Kumul Petroleum','https://kumulpetroleum.com/','png-public-enterprise'),S('credit-corp','Credit Corporation','https://www.creditcorporation.com.pg/','png-business')
  ]},
  {id:'context-png-public-sector',name:'PNG Government & Public Sector Context',task_title:'Research Context - PNG Government',sources:[
    S('dict-png','Department of ICT','https://www.ict.gov.pg/','png-government'),S('nicta-png','NICTA','https://www.nicta.gov.pg/','png-government'),S('treasury-png','Department of Treasury','https://www.treasury.gov.pg/','png-government'),S('finance-png','Department of Finance','https://www.finance.gov.pg/','png-government'),S('irc-png','Internal Revenue Commission','https://irc.gov.pg/','png-government'),S('bankpng','Bank of Papua New Guinea','https://www.bankpng.gov.pg/','png-government'),S('dpm-png','Department of Personnel Management','https://www.dpm.gov.pg/','png-government'),S('nso-png','National Statistical Office','https://www.nso.gov.pg/','png-government'),S('mra-png','Mineral Resources Authority','https://mra.gov.pg/','png-government'),S('health-png','Department of Health','https://www.health.gov.pg/','png-government'),S('justice-png','Department of Justice','https://www.justice.gov.pg/','png-government'),S('png-power','PNG Power','https://www.pngpower.com.pg/','png-public-enterprise')
  ]}
];

module.exports={pageExtras,contextCohorts};
