from pathlib import Path

path = Path('42-base.html')
html = path.read_text(encoding='utf-8')
old = """      const duration=220+Math.random()*120;\n      const started=performance.now();\n\n      const frame=now=>{\n        const t=Math.min(1,(now-started)/duration);\n        const headE=1-Math.pow(1-t,3);\n        const tailDelay=.24;\n        const tailProgress=Math.max(0,Math.min(1,(t-tailDelay)/(1-tailDelay)));\n        const tailE=1-Math.pow(1-tailProgress,3);\n        const headX=a.x+(b.x-a.x)*headE;\n        const headY=a.y+(b.y-a.y)*headE;\n        const tailX=a.x+(b.x-a.x)*tailE;\n        const tailY=a.y+(b.y-a.y)*tailE;\n        glow.setAttribute('x1',tailX);glow.setAttribute('y1',tailY);\n        glow.setAttribute('x2',headX);glow.setAttribute('y2',headY);\n        core.setAttribute('x1',tailX);core.setAttribute('y1',tailY);\n        core.setAttribute('x2',headX);core.setAttribute('y2',headY);\n        if(t<1){requestAnimationFrame(frame);return}\n        glow.remove();core.remove();\n      };\n      requestAnimationFrame(frame);\n"""
new = """      const duration=220+Math.random()*120;\n      const catchDuration=65;\n      const segmentPx=5;\n      const dx=b.x-a.x,dy=b.y-a.y;\n      const ctm=network.getScreenCTM();\n      const screenDx=ctm?ctm.a*dx+ctm.c*dy:dx;\n      const screenDy=ctm?ctm.b*dx+ctm.d*dy:dy;\n      const screenDistance=Math.max(1,Math.hypot(screenDx,screenDy));\n      const segmentProgress=Math.min(1,segmentPx/screenDistance);\n      const started=performance.now();\n\n      const frame=now=>{\n        const elapsed=now-started;\n        const travelT=Math.min(1,elapsed/duration);\n        const headE=1-Math.pow(1-travelT,3);\n        let tailE=Math.max(0,headE-segmentProgress);\n        let done=false;\n        if(travelT>=1){\n          const catchProgress=Math.min(1,(elapsed-duration)/catchDuration);\n          const catchE=1-Math.pow(1-catchProgress,3);\n          tailE=(1-segmentProgress)+segmentProgress*catchE;\n          done=catchProgress>=1;\n        }\n        const headX=a.x+(b.x-a.x)*headE;\n        const headY=a.y+(b.y-a.y)*headE;\n        const tailX=a.x+(b.x-a.x)*tailE;\n        const tailY=a.y+(b.y-a.y)*tailE;\n        glow.setAttribute('x1',tailX);glow.setAttribute('y1',tailY);\n        glow.setAttribute('x2',headX);glow.setAttribute('y2',headY);\n        core.setAttribute('x1',tailX);core.setAttribute('y1',tailY);\n        core.setAttribute('x2',headX);core.setAttribute('y2',headY);\n        if(!done){requestAnimationFrame(frame);return}\n        glow.remove();core.remove();\n      };\n      requestAnimationFrame(frame);\n"""
if old not in html:
    raise SystemExit('laser frame block not found, refusing to touch unrelated code')
html = html.replace(old, new, 1)
path.write_text(html, encoding='utf-8')
